"""
Exercise 3 - Build a per-variant interpretation report from a VEP-annotated VCF.

EDUCATIONAL AND RESEARCH USE ONLY. This file demonstrates how to
combine a VEP-annotated VCF with population-frequency and clinical-
knowledge data into a per-variant report. The output is not a
clinical interpretation. Do not use this code to make clinical
decisions. The same disclaimer that opens every Week 8 file applies.

Goal: parse the VEP CSQ INFO field with cyvcf2, integrate the
ClinVar / gnomAD lookups from Exercise 2, and emit a CSV plus an
HTML report. The exercise covers:

- Reading a VEP-annotated VCF with cyvcf2 (the fast Python VCF
  parser).
- Parsing the CSQ pipe-separated INFO field into per-transcript
  records and picking the canonical record.
- Parsing the SIFT and PolyPhen prediction-and-score strings.
- Building a pandas DataFrame with one row per variant.
- Rendering the frame as a CSV and as a standalone HTML page with
  the required disclaimer in the header.
- Recording a run-info JSON with the database versions and the
  date so the report is reproducible.

Estimated time: 90 minutes (30 min reading the VEP CSQ format,
45 min implementing the pipeline, 15 min running and inspecting
results).

Acceptance criteria:
- `python exercise-03-build-variant-report.py` runs end to end on
  the bundled `data/demo.vep.vcf` (from Exercise 1) without errors.
- The script's `--no-network` mode produces a complete report
  using only the bundled demo VCF and a stub ClinVar/gnomAD table
  (useful for CI and for offline study).
- `results/exercise-03-variants.csv` exists with at least the
  columns: chrom, pos, ref, alt, gene, consequence, impact,
  hgvsc, hgvsp, sift_pred, sift_score, polyphen_pred,
  polyphen_score, gnomad_af, gnomad_popmax_af, clinvar_clnsig,
  clinvar_clnrevstat.
- `results/exercise-03-variants.html` exists, contains the
  educational-use-only disclaimer at the top, and renders the
  same table.
- `results/exercise-03-run-info.json` exists and records the run
  date, VEP cache version (parsed from VCF header), and the
  database versions configured.

Requirements:
    pip install cyvcf2 pandas jinja2 requests
    (cyvcf2 requires htslib at build time; the conda recipe
    pre-builds it.)

What you learn:
- The cyvcf2 idiom for iterating a VCF and accessing INFO fields.
- The CSQ header parser pattern.
- The "pick canonical, fall back to first" logic for choosing a
  transcript record per variant.
- The pandas DataFrame.to_html() flow with custom CSS.
- The run-info JSON pattern for reproducibility.

Tool versions assumed:
- Python 3.11+
- cyvcf2 0.30+
- pandas 2.2+
- jinja2 3.1+
- VEP 110.1 (only needed if you regenerate the input VCF; this
  script only reads the output)
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import pandas as pd


# cyvcf2 is required for real use but heavy to install in CI. Make
# the import lazy so the --no-network demo can still run without it.
try:
    from cyvcf2 import VCF as _VCFReader  # type: ignore[import-not-found]
    HAS_CYVCF2: bool = True
except Exception:  # noqa: BLE001
    _VCFReader = None  # type: ignore[assignment]
    HAS_CYVCF2 = False


# ----------------------------------------------------------------------
# Disclaimer.
# ----------------------------------------------------------------------

DISCLAIMER: str = (
    "EDUCATIONAL AND RESEARCH USE ONLY. This report was generated by an "
    "automated pipeline for teaching purposes. It is not a clinical "
    "interpretation. Variant interpretation in a clinical context requires "
    "review by a CLIA-certified laboratory and a board-certified clinical "
    "geneticist. Do not act on this report."
)


# ----------------------------------------------------------------------
# CSQ parsing.
# ----------------------------------------------------------------------

def extract_csq_header(vcf_path: Path) -> list[str]:
    """Read the CSQ field order from a VEP-annotated VCF header.

    Args:
        vcf_path: path to the VEP-annotated VCF.

    Returns:
        Ordered list of CSQ field names. Empty list if the VCF has
        no CSQ INFO header.

    Raises:
        RuntimeError if cyvcf2 is not available.
    """
    if not HAS_CYVCF2 or _VCFReader is None:
        raise RuntimeError("cyvcf2 is required for VCF parsing; install it with conda or pip.")
    reader = _VCFReader(str(vcf_path))
    for line in reader.raw_header.splitlines():
        if not line.startswith("##INFO=<ID=CSQ"):
            continue
        marker: str = "Format: "
        idx: int = line.find(marker)
        if idx == -1:
            continue
        format_part: str = line[idx + len(marker):].rstrip('">')
        return format_part.split("|")
    return []


def parse_csq_field(csq_field: str, csq_header: list[str]) -> list[dict[str, str]]:
    """Split a VEP CSQ INFO string into per-transcript dicts.

    Args:
        csq_field:  the raw CSQ value (e.g.
            "A|missense_variant|MODERATE|...|,A|intron_variant|MODIFIER|...|").
            Multiple records are separated by commas; fields within a
            record by pipes.
        csq_header: ordered list of field names from the VCF header.

    Returns:
        list of dicts, one per overlapping transcript record.
    """
    if not csq_field:
        return []
    records: list[dict[str, str]] = []
    for raw in csq_field.split(","):
        fields: list[str] = raw.split("|")
        if len(fields) != len(csq_header):
            # Drop malformed records silently; do not crash.
            continue
        records.append(dict(zip(csq_header, fields)))
    return records


def pick_canonical_record(records: list[dict[str, str]]) -> dict[str, str]:
    """Choose the canonical CSQ record per variant.

    Preference order:
      1. The first record with CANONICAL == "YES".
      2. The first record with a non-empty MANE_SELECT.
      3. The first record overall.
      4. {} if there are no records.

    Args:
        records: list of CSQ-record dicts from parse_csq_field.

    Returns:
        The chosen record (or {}).
    """
    if not records:
        return {}
    canonical = next((r for r in records if r.get("CANONICAL") == "YES"), None)
    if canonical is not None:
        return canonical
    mane = next((r for r in records if r.get("MANE_SELECT")), None)
    if mane is not None:
        return mane
    return records[0]


# ----------------------------------------------------------------------
# SIFT / PolyPhen score parsing.
# ----------------------------------------------------------------------

_SCORE_PATTERN = re.compile(r"([a-zA-Z_]+)\(([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)\)")


def parse_prediction_and_score(field: str) -> tuple[str, float | None]:
    """Parse a VEP "prediction(score)" string.

    VEP's --sift b and --polyphen b emit strings like:
        deleterious(0.02)
        tolerated(0.5)
        probably_damaging(0.94)
        benign(0.05)
        unknown
        (empty string for variants without a score)

    Args:
        field: the raw VEP SIFT or PolyPhen field value.

    Returns:
        (prediction, score). prediction is "" if the field is empty.
        score is None if no numeric score is present.
    """
    if not field:
        return "", None
    match = _SCORE_PATTERN.match(field)
    if match is None:
        return field, None
    return match.group(1), float(match.group(2))


# ----------------------------------------------------------------------
# Per-variant row construction.
# ----------------------------------------------------------------------

@dataclass(frozen=True)
class DemoVariant:
    """A bundled demo variant used by --no-network mode."""
    chrom: str
    pos: int
    ref: str
    alt: str
    gene: str
    consequence: str
    impact: str
    hgvsc: str
    hgvsp: str
    sift_pred: str
    sift_score: float | None
    polyphen_pred: str
    polyphen_score: float | None
    rsid: str
    gnomad_af: float | None
    gnomad_popmax_af: float | None
    clinvar_clnsig: str
    clinvar_clnrevstat: str
    clinvar_clndn: str


DEMO_ROWS: list[DemoVariant] = [
    DemoVariant("chr17", 43094077, "G", "A", "BRCA1", "missense_variant", "MODERATE",
                "ENST00000357654.9:c.4837G>A", "ENSP00000350283.5:p.Glu1613Lys",
                "deleterious", 0.02, "probably_damaging", 0.94,
                "rs28897696", 0.00012, 0.00018,
                "Conflicting_interpretations_of_pathogenicity",
                "criteria_provided,_conflicting_classifications",
                "Hereditary breast and ovarian cancer syndrome"),
    DemoVariant("chr13", 32398489, "G", "A", "BRCA2", "stop_gained", "HIGH",
                "ENST00000380152.8:c.9976A>T", "ENSP00000369497.3:p.Lys3326Ter",
                "", None, "", None,
                "rs11571833", 0.005, 0.012,
                "Benign/Likely_benign",
                "criteria_provided,_multiple_submitters,_no_conflicts",
                "Hereditary breast and ovarian cancer syndrome"),
    DemoVariant("chr7", 117559590, "G", "A", "CFTR", "synonymous_variant", "LOW",
                "ENST00000003084.11:c.4521G>A", "",
                "", None, "", None,
                "rs1042077", 0.07, 0.18,
                "Benign", "criteria_provided,_multiple_submitters,_no_conflicts",
                "Cystic fibrosis"),
    DemoVariant("chr3", 37001008, "G", "A", "MLH1", "missense_variant", "MODERATE",
                "ENST00000231790.8:c.1853G>A", "ENSP00000231790.4:p.Arg618Gln",
                "deleterious", 0.01, "possibly_damaging", 0.65,
                "rs63751208", 0.0001, 0.00015,
                "Uncertain_significance", "criteria_provided,_single_submitter",
                "Lynch syndrome"),
    DemoVariant("chr2", 47403534, "C", "A", "MSH2", "missense_variant", "MODERATE",
                "ENST00000233146.7:c.1255C>A", "ENSP00000233146.6:p.Pro419Thr",
                "tolerated", 0.21, "benign", 0.05,
                "rs17217772", 0.0008, 0.002,
                "Likely_benign", "criteria_provided,_single_submitter",
                "Lynch syndrome"),
    DemoVariant("chr5", 112815473, "A", "T", "APC", "frameshift_variant", "HIGH",
                "ENST00000257430.9:c.3927_3931del", "ENSP00000257430.4:p.Glu1309fs",
                "", None, "", None,
                "", None, None,
                "Pathogenic", "reviewed_by_expert_panel",
                "Familial adenomatous polyposis"),
    DemoVariant("chr17", 7674220, "C", "T", "TP53", "stop_gained", "HIGH",
                "ENST00000269305.9:c.916C>T", "ENSP00000269305.4:p.Arg306Ter",
                "", None, "", None,
                "rs397514495", None, None,
                "Pathogenic", "reviewed_by_expert_panel",
                "Li-Fraumeni syndrome"),
    DemoVariant("chr11", 108235829, "G", "A", "ATM", "splice_donor_variant", "HIGH",
                "ENST00000675843.1:c.3576+1G>A", "",
                "", None, "", None,
                "", None, None,
                "Likely_pathogenic", "criteria_provided,_single_submitter",
                "Ataxia-telangiectasia"),
    DemoVariant("chr15", 48700503, "G", "A", "FBN1", "missense_variant", "MODERATE",
                "ENST00000316623.10:c.4789G>A", "ENSP00000325527.4:p.Glu1597Lys",
                "deleterious", 0.03, "probably_damaging", 0.89,
                "rs794728216", None, None,
                "Likely_pathogenic", "criteria_provided,_single_submitter",
                "Marfan syndrome"),
    DemoVariant("chr19", 11116107, "G", "A", "LDLR", "missense_variant", "MODERATE",
                "ENST00000252444.9:c.1646G>A", "ENSP00000252444.4:p.Gly549Asp",
                "deleterious", 0.00, "probably_damaging", 1.00,
                "rs28942078", None, None,
                "Pathogenic", "criteria_provided,_multiple_submitters,_no_conflicts",
                "Familial hypercholesterolemia"),
]


def demo_rows_to_dataframe(rows: list[DemoVariant]) -> pd.DataFrame:
    """Convert the in-memory DEMO_ROWS to a pandas frame."""
    records: list[dict[str, Any]] = []
    for r in rows:
        records.append({
            "chrom": r.chrom,
            "pos": r.pos,
            "ref": r.ref,
            "alt": r.alt,
            "gene": r.gene,
            "consequence": r.consequence,
            "impact": r.impact,
            "hgvsc": r.hgvsc,
            "hgvsp": r.hgvsp,
            "sift_pred": r.sift_pred,
            "sift_score": r.sift_score,
            "polyphen_pred": r.polyphen_pred,
            "polyphen_score": r.polyphen_score,
            "rsid": r.rsid,
            "gnomad_af": r.gnomad_af,
            "gnomad_popmax_af": r.gnomad_popmax_af,
            "clinvar_clnsig": r.clinvar_clnsig,
            "clinvar_clnrevstat": r.clinvar_clnrevstat,
            "clinvar_clndn": r.clinvar_clndn,
        })
    return pd.DataFrame(records)


def parse_annotated_vcf(vcf_path: Path) -> pd.DataFrame:
    """Read a VEP-annotated VCF and return a per-variant frame.

    Args:
        vcf_path: path to the VEP-annotated VCF.

    Returns:
        pandas DataFrame with one row per variant, columns matching
        DEMO_ROWS.

    Raises:
        RuntimeError if cyvcf2 is not available.
    """
    if not HAS_CYVCF2 or _VCFReader is None:
        raise RuntimeError("cyvcf2 is required for VCF parsing; install it with conda or pip.")

    csq_header: list[str] = extract_csq_header(vcf_path)
    if not csq_header:
        raise RuntimeError(f"{vcf_path} has no CSQ INFO header; was it annotated by VEP?")

    records: list[dict[str, Any]] = []
    reader = _VCFReader(str(vcf_path))
    for variant in reader:
        csq_raw: str = variant.INFO.get("CSQ", "") or ""
        all_records: list[dict[str, str]] = parse_csq_field(csq_raw, csq_header)
        canonical: dict[str, str] = pick_canonical_record(all_records)

        sift_pred, sift_score = parse_prediction_and_score(canonical.get("SIFT", ""))
        pp_pred, pp_score = parse_prediction_and_score(canonical.get("PolyPhen", ""))

        gnomade_af_raw: str = canonical.get("gnomADe_AF", "") or ""
        gnomadg_af_raw: str = canonical.get("gnomADg_AF", "") or ""
        gnomade_af: float | None = _parse_float_or_none(gnomade_af_raw)
        gnomadg_af: float | None = _parse_float_or_none(gnomadg_af_raw)
        # If both are present, take the exome AF as the primary
        # (matches the ACMG convention; the genome AF is recorded
        # separately for completeness).
        primary_af: float | None = gnomade_af if gnomade_af is not None else gnomadg_af

        records.append({
            "chrom": variant.CHROM,
            "pos": int(variant.POS),
            "ref": variant.REF,
            "alt": ",".join(variant.ALT) if variant.ALT else "",
            "gene": canonical.get("SYMBOL", ""),
            "consequence": canonical.get("Consequence", ""),
            "impact": canonical.get("IMPACT", ""),
            "hgvsc": canonical.get("HGVSc", ""),
            "hgvsp": canonical.get("HGVSp", ""),
            "sift_pred": sift_pred,
            "sift_score": sift_score,
            "polyphen_pred": pp_pred,
            "polyphen_score": pp_score,
            "rsid": canonical.get("Existing_variation", ""),
            "gnomad_af": primary_af,
            "gnomad_popmax_af": None,
            "clinvar_clnsig": "",
            "clinvar_clnrevstat": "",
            "clinvar_clndn": "",
        })
    return pd.DataFrame(records)


def _parse_float_or_none(raw: str) -> float | None:
    if not raw:
        return None
    try:
        return float(raw)
    except ValueError:
        return None


# ----------------------------------------------------------------------
# Optional join with the ClinVar/gnomAD TSV from Exercise 2.
# ----------------------------------------------------------------------

def join_with_exercise_02(report: pd.DataFrame, exercise_02_tsv: Path) -> pd.DataFrame:
    """Merge the report frame with the Exercise 2 TSV on coordinates.

    The Exercise 2 TSV has chrom (no "chr" prefix); the VEP VCF has
    "chr" prefixes. Normalize before joining.
    """
    if not exercise_02_tsv.exists():
        print(f"  [warn] {exercise_02_tsv} not found; skipping ClinVar/gnomAD join.")
        return report
    ex02: pd.DataFrame = pd.read_csv(exercise_02_tsv, sep="\t")
    ex02 = ex02.copy()
    ex02["chrom_norm"] = ex02["chrom"].astype(str).str.replace("^chr", "", regex=True)
    report = report.copy()
    report["chrom_norm"] = report["chrom"].astype(str).str.replace("^chr", "", regex=True)
    merged: pd.DataFrame = report.merge(
        ex02[["chrom_norm", "pos", "ref", "alt", "gnomad_af", "gnomad_popmax_af",
              "clinvar_clnsig", "clinvar_clnrevstat", "clinvar_clndn"]],
        on=["chrom_norm", "pos", "ref", "alt"],
        how="left",
        suffixes=("", "_ex02"),
    )
    # Prefer Exercise-2 values over the VEP-bundled gnomAD AF when present.
    for col in ("gnomad_af", "gnomad_popmax_af", "clinvar_clnsig",
                "clinvar_clnrevstat", "clinvar_clndn"):
        ex02_col: str = f"{col}_ex02"
        if ex02_col in merged.columns:
            merged[col] = merged[ex02_col].combine_first(merged[col])
            merged = merged.drop(columns=[ex02_col])
    merged = merged.drop(columns=["chrom_norm"])
    return merged


# ----------------------------------------------------------------------
# Output.
# ----------------------------------------------------------------------

HTML_TEMPLATE: str = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>C10 Week 8 - Variant Annotation Report (Educational)</title>
<style>
 body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
        color: #1a1a1a; max-width: 1200px; margin: 2em auto; padding: 0 1em; }
 h1 { border-bottom: 2px solid #1a1a1a; padding-bottom: 0.2em; }
 .disclaimer { background: #fff7d6; border: 1px solid #e0a800;
               padding: 0.8em 1em; margin-bottom: 1.5em; font-size: 0.95em; }
 .meta { background: #f5f5f5; padding: 0.6em 1em; font-size: 0.85em;
          margin-bottom: 1em; }
 table { border-collapse: collapse; font-size: 0.85em; }
 th, td { border: 1px solid #ddd; padding: 0.3em 0.6em; text-align: left;
          vertical-align: top; }
 th { background: #f0f0f0; font-weight: 600; }
 .impact-HIGH { background: #fde2e2; }
 .impact-MODERATE { background: #fff2cc; }
 .impact-LOW { background: #e6f3d4; }
 .impact-MODIFIER { background: #eee; }
</style>
</head>
<body>
<h1>Variant Annotation Report</h1>
<div class="disclaimer"><strong>Educational and research use only.</strong>
{{ disclaimer }}</div>
<div class="meta">
 <strong>Run date:</strong> {{ run_date }}<br>
 <strong>Input VCF:</strong> {{ input_vcf }}<br>
 <strong>VEP cache version:</strong> {{ vep_cache_version }}<br>
 <strong>ClinVar release:</strong> {{ clinvar_release }}<br>
 <strong>gnomAD version:</strong> {{ gnomad_version }}<br>
 <strong>Total variants:</strong> {{ n_variants }}
</div>
{{ table_html | safe }}
<p style="font-size: 0.8em; color: #666; margin-top: 2em;">
Generated by exercise-03-build-variant-report.py in C10 Week 8.
Educational and research use only. Not for clinical decision-making.
</p>
</body>
</html>
"""


def render_html_report(report: pd.DataFrame, output_path: Path,
                        run_info: dict[str, Any]) -> None:
    """Render the per-variant frame as a standalone HTML report."""
    table_html: str = report.to_html(index=False, na_rep="", escape=True,
                                       classes="report-table")

    # Manual templating (no Jinja2 required for this simple form),
    # but the placeholders use Jinja-like syntax for readability.
    html: str = HTML_TEMPLATE
    replacements: dict[str, str] = {
        "{{ disclaimer }}": DISCLAIMER.split(". ", 1)[1].rstrip("."),
        "{{ run_date }}": str(run_info.get("run_date", "")),
        "{{ input_vcf }}": str(run_info.get("input_vcf", "")),
        "{{ vep_cache_version }}": str(run_info.get("vep_cache_version", "")),
        "{{ clinvar_release }}": str(run_info.get("clinvar_release", "")),
        "{{ gnomad_version }}": str(run_info.get("gnomad_version", "")),
        "{{ n_variants }}": str(run_info.get("n_variants", len(report))),
        "{{ table_html | safe }}": table_html,
    }
    for key, value in replacements.items():
        html = html.replace(key, value)
    output_path.write_text(html, encoding="utf-8")


# ----------------------------------------------------------------------
# CLI.
# ----------------------------------------------------------------------

def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build a per-variant interpretation report from a VEP-"
                    "annotated VCF. Educational and research use only. Not "
                    "for clinical decision-making."
    )
    parser.add_argument("--vcf", type=Path,
                        default=Path(__file__).parent / "data" / "demo.vep.vcf",
                        help="Input VEP-annotated VCF.")
    parser.add_argument("--ex02-tsv", type=Path,
                        default=Path(__file__).parent / "results" / "exercise-02-clinvar-gnomad.tsv",
                        help="Exercise 2 output TSV (ClinVar + gnomAD).")
    parser.add_argument("--out-csv", type=Path,
                        default=Path(__file__).parent / "results" / "exercise-03-variants.csv",
                        help="Output CSV.")
    parser.add_argument("--out-html", type=Path,
                        default=Path(__file__).parent / "results" / "exercise-03-variants.html",
                        help="Output HTML.")
    parser.add_argument("--out-run-info", type=Path,
                        default=Path(__file__).parent / "results" / "exercise-03-run-info.json",
                        help="Output run-info JSON.")
    parser.add_argument("--clinvar-release", type=str, default="2024-09-01",
                        help="ClinVar VCF release date (recorded in run-info JSON).")
    parser.add_argument("--gnomad-version", type=str, default="v4.1.0",
                        help="gnomAD version (recorded in run-info JSON).")
    parser.add_argument("--vep-cache-version", type=str, default="110",
                        help="VEP cache version (recorded in run-info JSON).")
    parser.add_argument("--no-network", action="store_true",
                        help="Skip VCF parsing and use the bundled demo rows.")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    args.out_csv.parent.mkdir(parents=True, exist_ok=True)

    if args.no_network or not args.vcf.exists() or not HAS_CYVCF2:
        if not args.no_network:
            print(f"  [info] Falling back to bundled demo rows: vcf exists={args.vcf.exists()}, "
                  f"cyvcf2 available={HAS_CYVCF2}.")
        report = demo_rows_to_dataframe(DEMO_ROWS)
        input_label: str = "demo (in-memory)"
    else:
        print(f"  [info] Parsing {args.vcf} with cyvcf2 ...")
        report = parse_annotated_vcf(args.vcf)
        input_label = str(args.vcf)
        if args.ex02_tsv.exists():
            print(f"  [info] Joining with {args.ex02_tsv} ...")
            report = join_with_exercise_02(report, args.ex02_tsv)

    # Write CSV.
    report.to_csv(args.out_csv, index=False)
    print(f"  [info] wrote {args.out_csv} with {len(report)} rows.")

    # Write run-info JSON.
    run_info: dict[str, Any] = {
        "run_date": dt.datetime.now().date().isoformat(),
        "input_vcf": input_label,
        "vep_cache_version": args.vep_cache_version,
        "clinvar_release": args.clinvar_release,
        "gnomad_version": args.gnomad_version,
        "n_variants": int(len(report)),
        "disclaimer": DISCLAIMER,
    }
    args.out_run_info.write_text(json.dumps(run_info, indent=2, sort_keys=True), encoding="utf-8")
    print(f"  [info] wrote {args.out_run_info}.")

    # Write HTML.
    render_html_report(report, args.out_html, run_info)
    print(f"  [info] wrote {args.out_html}.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
