"""
Mini-project starter - End-to-end variant annotation and interpretation pipeline.

EDUCATIONAL AND RESEARCH USE ONLY. This pipeline produces a per-variant
interpretation report. The report is not a clinical interpretation. Variant
interpretation in a clinical context requires a CLIA-certified laboratory
and a board-certified clinical geneticist. Do not act on this report.

This file is a SKELETON. It compiles cleanly under `python3 -m py_compile`
but most functions raise NotImplementedError. Your job is to fill in the
TODOs to produce a working `annotate(vcf_path, ref_dir, out_dir) -> Path`
function that runs the seven-stage pipeline described in README.md:

  1. validate_input(vcf_path)
  2. run_vep(vcf_path, vep_cache_dir, out_path)
  3. run_snpeff(vcf_path, snpeff_db, out_path)
  4. query_gnomad_bulk(variants, cache_dir, dataset)
  5. query_clinvar_bulk(variants, clinvar_vcf)
  6. apply_acmg_classifier(report_frame, lof_gene_set)
  7. write_outputs(report_frame, out_dir, run_info)

Each function has a docstring, a type signature, and a NotImplementedError.
Replace the body with your implementation. The acceptance criteria in
README.md tell you what each function must produce.

Tool versions assumed:
- Python 3.11+
- VEP 110.1, SnpEff 5.2 (CLI tools; subprocess.run them)
- cyvcf2 0.30+, pandas 2.2+, requests 2.32+
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import shelve
import subprocess
import sys
import time
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any


# ----------------------------------------------------------------------
# Disclaimer (used on every output).
# ----------------------------------------------------------------------

DISCLAIMER: str = (
    "EDUCATIONAL AND RESEARCH USE ONLY. This report was generated by an "
    "automated pipeline for teaching purposes. It is not a clinical "
    "interpretation. Variant interpretation in a clinical context requires "
    "review by a CLIA-certified laboratory and a board-certified clinical "
    "geneticist. Do not act on this report."
)


# ----------------------------------------------------------------------
# Stage 1 - input validation.
# ----------------------------------------------------------------------

@dataclass
class PipelineRunInfo:
    """Provenance metadata recorded on every run.

    Every field must be filled in before the pipeline writes the
    run-info JSON. Empty values are silently wrong; assert non-empty
    before writing.
    """
    run_date: str = ""
    input_vcf: str = ""
    vep_version: str = "110.1"
    vep_cache_version: str = "110"
    snpeff_version: str = "5.2"
    snpeff_db: str = "GRCh38.105"
    clinvar_release: str = ""
    gnomad_version: str = "v4.1.0"
    assembly: str = "GRCh38"
    n_variants: int = 0
    disclaimer: str = DISCLAIMER


def validate_input(vcf_path: Path) -> int:
    """Validate the input VCF.

    Checks:
      - The file exists.
      - The file has a `##reference=GRCh38` header (or `##contig=` with
        a recognized chromosome name).
      - The file has at least one variant record.

    Args:
        vcf_path: path to the input VCF.

    Returns:
        The number of variants in the input VCF.

    Raises:
        FileNotFoundError: if the VCF is not present.
        ValueError: if the VCF is empty or has no GRCh38 reference.
    """
    # TODO: implement.
    raise NotImplementedError("Implement validate_input as Stage 1.")


# ----------------------------------------------------------------------
# Stage 2 - VEP annotation.
# ----------------------------------------------------------------------

def run_vep(input_vcf: Path, vep_cache_dir: Path, out_vcf: Path,
            cache_version: int = 110, threads: int = 4,
            force: bool = False) -> Path:
    """Run VEP on the input VCF.

    Skips the run if `out_vcf` exists and is newer than `input_vcf`
    and `force` is False.

    The required VEP flags:
        --vcf --cache --dir_cache <vep_cache_dir> --offline
        --species homo_sapiens --assembly GRCh38
        --cache_version <cache_version>
        --sift b --polyphen b
        --canonical --mane --symbol --biotype
        --af --af_gnomadg --af_gnomade
        --check_existing
        --fork <threads> --force_overwrite --no_stats

    Args:
        input_vcf:     path to the input VCF.
        vep_cache_dir: path to the VEP cache directory (e.g. ~/.vep).
        out_vcf:       path to write the annotated VCF.
        cache_version: VEP cache release version (default 110).
        threads:       number of fork worker processes.
        force:         if True, re-run even if out_vcf is up to date.

    Returns:
        out_vcf (after successful run).

    Raises:
        subprocess.CalledProcessError: on non-zero exit from VEP.
        FileNotFoundError: if vep is not on PATH.
    """
    # TODO: implement using subprocess.run([...], check=True).
    raise NotImplementedError("Implement run_vep as Stage 2.")


# ----------------------------------------------------------------------
# Stage 3 - SnpEff annotation.
# ----------------------------------------------------------------------

def run_snpeff(input_vcf: Path, snpeff_db: str, out_vcf: Path,
               force: bool = False) -> Path:
    """Run SnpEff on the input VCF.

    Skips if `out_vcf` is newer than `input_vcf` and `force` is False.

    Args:
        input_vcf: path to the input VCF.
        snpeff_db: SnpEff database name (e.g. "GRCh38.105").
        out_vcf:   path to write the annotated VCF.
        force:     if True, re-run even if out_vcf is up to date.

    Returns:
        out_vcf.

    Raises:
        subprocess.CalledProcessError: on non-zero exit from snpEff.
    """
    # TODO: implement using subprocess.run.
    raise NotImplementedError("Implement run_snpeff as Stage 3.")


def compute_vep_snpeff_disagreements(vep_vcf: Path, snpeff_vcf: Path,
                                      out_txt: Path) -> int:
    """Compare per-variant IMPACT between VEP and SnpEff; write a report.

    For each variant present in both annotated VCFs, compare the
    impact tier of the canonical (VEP) and first (SnpEff) record.
    Disagreements are written to `out_txt` as a tab-separated table:
        chrom  pos  ref  alt  vep_impact  snpeff_impact  vep_consequence  snpeff_consequence

    Args:
        vep_vcf:    path to VEP-annotated VCF.
        snpeff_vcf: path to SnpEff-annotated VCF.
        out_txt:    output path for the disagreement report.

    Returns:
        The number of disagreement rows written.
    """
    # TODO: implement.
    raise NotImplementedError("Implement compute_vep_snpeff_disagreements.")


# ----------------------------------------------------------------------
# Stage 4 - gnomAD queries (with cache).
# ----------------------------------------------------------------------

def query_gnomad_bulk(variants: list[tuple[str, int, str, str]],
                      cache_dir: Path,
                      dataset: str = "gnomad_r4") -> dict[str, dict[str, Any]]:
    """Query gnomAD for a list of variants. Cache responses on disk.

    Args:
        variants:  list of (chrom_no_chr, pos, ref, alt) tuples.
        cache_dir: directory for the shelve cache files.
        dataset:   gnomAD dataset (default v4.1 combined).

    Returns:
        dict mapping variant ID ("chrom-pos-ref-alt") to the parsed
        gnomAD response dict; empty dict {} for variants absent from
        gnomAD (informative for ACMG PM2).
    """
    # TODO: implement using a shelve cache and the polite-retry HTTP pattern.
    raise NotImplementedError("Implement query_gnomad_bulk as Stage 4.")


# ----------------------------------------------------------------------
# Stage 5 - ClinVar queries (via local tabix).
# ----------------------------------------------------------------------

def query_clinvar_bulk(variants: list[tuple[str, int, str, str]],
                       clinvar_vcf: Path) -> dict[str, dict[str, str]]:
    """Query the local ClinVar VCF for a list of variants.

    Uses cyvcf2's tabix-style region access. For each input variant,
    iterates the ClinVar records overlapping the coordinate and emits
    the first record whose REF + ALT match.

    Args:
        variants:    list of (chrom_with_chr, pos, ref, alt) tuples.
                     Note: ClinVar VCFs use "chr" prefixes; strip or
                     add as needed.
        clinvar_vcf: path to the local ClinVar release (.vcf.gz with
                     .tbi index).

    Returns:
        dict mapping "chrom:pos:ref:alt" to a dict with keys
        clnsig, clnrevstat, clndn, clndisdb, rs, geneinfo, mc.
        Empty dict {} for variants absent from ClinVar (also
        informative).
    """
    # TODO: implement.
    raise NotImplementedError("Implement query_clinvar_bulk as Stage 5.")


# ----------------------------------------------------------------------
# Stage 6 - ACMG classifier.
# ----------------------------------------------------------------------

class ACMGClassification(str, Enum):
    PATHOGENIC = "Pathogenic"
    LIKELY_PATHOGENIC = "Likely_pathogenic"
    UNCERTAIN_SIGNIFICANCE = "Uncertain_significance"
    LIKELY_BENIGN = "Likely_benign"
    BENIGN = "Benign"


@dataclass
class ACMGEvidence:
    pathogenic_very_strong: set[str] = field(default_factory=set)
    pathogenic_strong: set[str] = field(default_factory=set)
    pathogenic_moderate: set[str] = field(default_factory=set)
    pathogenic_supporting: set[str] = field(default_factory=set)
    benign_standalone: set[str] = field(default_factory=set)
    benign_strong: set[str] = field(default_factory=set)
    benign_supporting: set[str] = field(default_factory=set)
    skipped: set[str] = field(default_factory=set)
    warnings: list[str] = field(default_factory=list)


def apply_acmg_classifier(report_frame: Any, lof_gene_set: frozenset[str]
                          ) -> Any:
    """Apply the mechanically computable ACMG criteria.

    Adds columns to the per-variant frame:
        acmg_classification, acmg_evidence, skipped_criteria, acmg_warnings.

    The eight mechanically computable criteria:
        PVS1 (with the LOF gene list)
        PM2 (gnomad_popmax_af < 0.0001 or absent)
        PM4 (inframe indel or stop_lost; not in a repeat)
        PP3 (SIFT < 0.05 AND PolyPhen > 0.85)
        BA1 (gnomad_popmax_af > 0.05)
        BS2 (gnomad_hom_count > 0 for a recessive disorder)
        BP4 (SIFT > 0.05 AND PolyPhen < 0.5)
        BP7 (synonymous, not in a splice region)

    Args:
        report_frame: pandas DataFrame from Stage 5 (per-variant frame
                       with VEP + gnomAD + ClinVar columns).
        lof_gene_set: gene symbols where LOF is a known disease
                       mechanism (ClinGen Haploinsufficiency Tier 3).

    Returns:
        the augmented DataFrame.
    """
    # TODO: implement; refer to lecture-notes/03 and challenges/challenge-01.
    raise NotImplementedError("Implement apply_acmg_classifier as Stage 6.")


# ----------------------------------------------------------------------
# Stage 7 - output writing.
# ----------------------------------------------------------------------

def write_outputs(report_frame: Any, out_dir: Path,
                  run_info: PipelineRunInfo) -> Path:
    """Write the per-variant CSV, the HTML report, and the run-info JSON.

    Args:
        report_frame: pandas DataFrame with the ACMG classifier output.
        out_dir:      directory for the output files.
        run_info:     provenance metadata.

    Returns:
        path to the HTML report.
    """
    # TODO: implement.
    raise NotImplementedError("Implement write_outputs as Stage 7.")


# ----------------------------------------------------------------------
# Orchestration entrypoint.
# ----------------------------------------------------------------------

def annotate(vcf_path: Path, ref_dir: Path, out_dir: Path) -> Path:
    """Run the full seven-stage pipeline.

    Args:
        vcf_path: path to the input VCF.
        ref_dir:  directory holding the ClinVar VCF, LOF gene list, etc.
        out_dir:  directory for outputs.

    Returns:
        path to the HTML report.
    """
    # 1. Validate input.
    n: int = validate_input(vcf_path)

    # 2. VEP.
    vep_vcf: Path = out_dir / "demo.vep.vcf"
    run_vep(vcf_path, vep_cache_dir=Path.home() / ".vep", out_vcf=vep_vcf)

    # 3. SnpEff.
    snpeff_vcf: Path = out_dir / "demo.snpeff.vcf"
    run_snpeff(vcf_path, snpeff_db="GRCh38.105", out_vcf=snpeff_vcf)

    disagreement_path: Path = out_dir / "disagreement_report.txt"
    n_disagree: int = compute_vep_snpeff_disagreements(vep_vcf, snpeff_vcf,
                                                       disagreement_path)

    # 4. gnomAD.
    # TODO: parse vep_vcf, build variant list, call query_gnomad_bulk.

    # 5. ClinVar.
    # TODO: build variant list, call query_clinvar_bulk.

    # 6. ACMG.
    # TODO: build the per-variant pandas frame; call apply_acmg_classifier.

    # 7. Write outputs.
    run_info = PipelineRunInfo(
        run_date=dt.datetime.now().date().isoformat(),
        input_vcf=str(vcf_path),
        clinvar_release="2024-09-01",
        n_variants=n,
    )
    # TODO: pass the frame and run_info to write_outputs.

    raise NotImplementedError(
        "annotate() needs Stages 4, 5, 6, 7 wired up. "
        "See README.md acceptance criteria."
    )


# ----------------------------------------------------------------------
# CLI.
# ----------------------------------------------------------------------

def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="End-to-end variant annotation pipeline. "
                    "Educational and research use only. "
                    "Not for clinical decision-making."
    )
    parser.add_argument("--vcf", type=Path,
                        default=Path("data") / "demo.vcf",
                        help="Input VCF.")
    parser.add_argument("--ref-dir", type=Path, default=Path("data"),
                        help="Reference directory.")
    parser.add_argument("--out-dir", type=Path, default=Path("results"),
                        help="Output directory.")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    args.out_dir.mkdir(parents=True, exist_ok=True)
    try:
        report_path: Path = annotate(args.vcf, args.ref_dir, args.out_dir)
    except NotImplementedError as exc:
        print(f"[starter] STAGE NOT IMPLEMENTED: {exc}", file=sys.stderr)
        print("[starter] This is a skeleton; fill in the TODOs.", file=sys.stderr)
        return 2
    print(f"[mini-project] wrote {report_path}.")
    print(f"[mini-project] DISCLAIMER: {DISCLAIMER}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
